import loadable from '@loadable/component'

export const HeroVideo = loadable(() => import('./HeroVideo'))
export const HeroQuote = loadable(() => import('./HeroQuote'))
export const CtaSection = loadable(() => import('./CTASection'), {ssr: false})
export const HeroSection = loadable(() => import('./HeroSection'))
export const LongSection = loadable(() => import('./LongSection'), {ssr: false})
export const CardsSection = loadable(() => import('./CardsSection'), {ssr: false})
export const ImageSection = loadable(() => import('./ImageSection'), {ssr: false})
export const ImageTextSection = loadable(() => import('./ImageTextSection'), {ssr: false})
export const QuoteSection = loadable(() => import('./QuoteSection'), {ssr: false})
export const ValuesSection = loadable(() => import('./ValuesSection'), {ssr: false})
export const SliderSection = loadable(() => import('./SliderSection'), {ssr: false})
export const ContentSection = loadable(() => import('./ContentSection'), {ssr: false})
export const SessionSection = loadable(() => import('./SessionSection'), {ssr: false})
export const HeroInfoSection = loadable(() => import('./HeroInfoSection'))
export const HeroImageAndForm = loadable(() => import('./HeroImageAndForm'))
export const HeroVideoAndForm = loadable(() => import('./HeroVideoAndForm'))
export const CapabilitiesSection = loadable(() => import('./CapabilitiesSection'), {ssr: false})
export const OpeningsPressSection = loadable(() => import('./OpeningsPressSection'), {ssr: false})
export const CustomerStoriesSection = loadable(() => import('./CustomerStoriesSection'), {
  ssr: false,
})
export const CategoriesWithBlogsSection = loadable(() => import('./CategoriesWithBlogsSection'), {
  ssr: false,
})
export const HeroCTAForm = loadable(() => import('./HeroCTAForm'))
export const HeroCTAFormSection = loadable(() => import('./HeroCTAFormSection'))
export const HostsSection = loadable(() => import('./HostsSection'), {ssr: false})
export const MostPopularSection = loadable(() => import('./MostPopularSection'), {ssr: false})
export const ContactusSection = loadable(() => import('./ContactusSection'), {ssr: false})
export const CareersHeroSection = loadable(() => import('./CareersHeroSection'))
export const OpeningsSection = loadable(() => import('./OpeningsSection'), {ssr: false})
export const LeadershipSection = loadable(() => import('./LeadershipSection'), {ssr: false})
export const ArticlesPressSection = loadable(() => import('./ArticlesPressSection'), {ssr: false})
export const AwardsSection = loadable(() => import('./AwardsSection'), {
  ssr: false,
})
export const MeasureSection = loadable(() => import('./MeasureSection'), {ssr: false})
export const OurCustomersSection = loadable(() => import('./OurCustomersSection'), {ssr: false})
export const TabsSection = loadable(() => import('./TabsSection'), {ssr: false})
export const LandingpageFooter = loadable(() => import('./LandingpageFooter'), {ssr: false})
export const LandingCardsSection = loadable(() => import('./LandingCardsSection'), {
  ssr: false,
})
export const HeroForm = loadable(() => import('./HeroForm'))
export const HeroFormSustainability = loadable(() => import('./HeroFormSustainability'))
export const LandingTemplateSustainability = loadable(
  () => import('./LandingTemplateSustainability'),
  {
    ssr: false,
  }
)
export const SustainCardsSection = loadable(() => import('./SustainCardsSection'), {ssr: false})
export const HeroFormVideo = loadable(() => import('./HeroFormVideo'))
export const HeroCTASection = loadable(() => import('./HeroCTASection'))
export const UpcomingEventSection = loadable(() => import('./UpcomingEventSection'), {ssr: false})
export const GoogleFAQSection = loadable(() => import('./GoogleFAQSection'), {ssr: false})
export const BlogCardsSection = loadable(() => import('./BlogCardsSection'), {ssr: false})
export const HeroReport = loadable(() => import('./HeroReport'))
export const TabsVerticalSection = loadable(() => import('./TabsVerticalSection'), {ssr: false})
export const SliderReportSection = loadable(() => import('./SliderReportSection'), {ssr: false})
export const TableImage = loadable(() => import('./TableImage'), {ssr: false})
export const CardsSectionReport = loadable(() => import('./CardsSectionReport'), {ssr: false})

export const ProductTemplate = loadable(() => import('./ProductTemplate'))
export const ProductVideoTemplate = loadable(() => import('./ProductVideoTemplate'))
export const CareersTemplate = loadable(() => import('./CareersTemplate'))
export const ContactusTemplate = loadable(() => import('./ContactusTemplate'))
export const CustomersTemplate = loadable(() => import('./CustomersTemplate'))
export const ResourcesTemplate = loadable(() => import('./ResourcesTemplate'))
export const WhyWespireTemplate = loadable(() => import('./WhyWespireTemplate'))
export const LeadershipTemplate = loadable(() => import('./LeadershipTemplate'))
export const WespireLiveTemplate = loadable(() => import('./WespireLiveTemplate'))
export const RequestDemoTemplate = loadable(() => import('./RequestDemoTemplate'))
export const PrivacyPolicyTemplate = loadable(() => import('./PrivacyPolicyTemplate'))
export const SolutionsOverviewTemplate = loadable(() => import('./SolutionsOverviewTemplate'))
export const NewsRoomTemplate = loadable(() => import('./NewsRoomTemplate'))
export const LandingTemplate = loadable(() => import('./LandingTemplate'))
export const LandingTemplateCompetitor = loadable(() => import('./LandingTemplateCompetitor'))
export const LandingTemplateSocialProof = loadable(() => import('./LandingTemplateSocialProof'))
export const LandingVideoTemplate = loadable(() => import('./LandingVideoTemplate'))
export const PersonaTemplate = loadable(() => import('./PersonaTemplate'))
export const HomeTemplate = loadable(() => import('./HomeTemplate'))
export const LandingTemplateReport = loadable(() => import('./LandingTemplateReport'))
