export {default as HeroSection} from './HeroSection'
export {default as LongSection} from './LongSection'
export {default as SliderSection} from './SliderSection'
export {default as CardsSection} from './CardsSection'
export {default as CtaSection} from './CTASection'
// export {default as TextSection} from './TextSection'
// export {default as ImageSection} from './ImageSection'
