
name: Sanity Automated Backup 
on:
  schedule:
    # Runs at 10:00 on every 5th day-of-month.
    - cron: "0 10 */5 * *"
  workflow_dispatch:
jobs:
  backup-dataset:
    runs-on: ubuntu-latest
    name: Backup dataset
    defaults:
      run:
        working-directory: studio
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i --legacy-peer-deps
        
      - name: Export dataset
        run: |
            SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" \
            npx sanity dataset export \
            production backups/backup.tar.gz
            
      - name: Upload backup.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: backup-tarball
          path: studio/backups/backup.tar.gz
          if-no-files-found: error

 
    
